spring.application.name=Ai-event-app
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=lVOCaUWIAjTAwRUurtUsxSNvBQWjxOCq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
gemini.api.key=${GEMINI_API_KEY:Your Api key }
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
